name: CICD pipeline view

on:
  push:
    branches: ["main"]

jobs:
  build-node:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

  build-docker:
     runs-on: ubuntu-latest

     steps:
       - name: checkout code
         uses: actions/checkout@v4

       - name: Set-up-docker
         uses: docker/setup-docker-action@v5
         with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}


  docker-push:
     needs: build-docker
     runs-on: ubuntu-latest


     steps:
       - name: Build and push
         uses: docker/build-and-push@v7
         with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/demo-app/${github.run_id}

 

           

     


        
  
    
          
     
     
    
          

      
        
     
